title: GameChanger Guide
email: fosterb@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Helping scorekeepers, coaches, and teams get the most out of GameChanger
baseurl: ""
url: "gcguide.github.io"
twitter_username: phostershop
github_username:  fosterbrereton

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman
plugins:
  - jekyll-feed
show_downloads: false
github:
  - is_project_page: false
exclude:
  - Gemfile.lock
